### ISSUE TITLE
Aptos AddrAggregator requires support for other addresses

### ISSUE THREAD

**Issue by 99Kies** [NonceGeek/DID-Solution-In-Move#19]
1. There are several lengths of addresses on Move that we need to support.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/45918704/193174725-d8b5b9b9-d7d2-4d70-bf92-475a178f535c.png">

2. ETH Address

`Bounty: 400xUsdt`

**Comment by leeduckgo** [comment]
> https://stcscan.io/main/transactions/detail/0x9acc7cbebb3e514da4d04dddc5cf0a268cdeb6b6ff84342e06af59708c79b74e
